on: 
  push:

  jobs:
    test:
      runs-on: ubuntu-latest

    steps:
    - name : Checkout
      uses : actions/checkout@v3
    - name : Print
      run : echo "Hello Github Actions !"
    - name : List
      run : ls -la
